# Generated by Django 2.2.5 on 2019-09-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sagenkarta-Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'managed': False, 'verbose_name': 'Uppteckning/inspelning', 'verbose_name_plural': 'Uppteckningar och inspelningar'},
        ),
        migrations.AlterField(
            model_name='transcribedrecordscategory',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.PROTECT, to='Sagenkarta-Admin.Categories'),
        ),
        migrations.AlterField(
            model_name='transcribedrecordscategory',
            name='record',
            field=models.ForeignKey(db_column='record', on_delete=django.db.models.deletion.PROTECT, to='Sagenkarta-Admin.TranscribedRecords'),
        ),
        migrations.AlterField(
            model_name='transcribedrecordspersons',
            name='person',
            field=models.ForeignKey(db_column='person', on_delete=django.db.models.deletion.PROTECT, to='Sagenkarta-Admin.Persons'),
        ),
        migrations.AlterField(
            model_name='transcribedrecordspersons',
            name='record',
            field=models.ForeignKey(db_column='record', on_delete=django.db.models.deletion.PROTECT, to='Sagenkarta-Admin.TranscribedRecords'),
        ),
        migrations.AlterField(
            model_name='transcribedrecordsplaces',
            name='place',
            field=models.ForeignKey(db_column='place', on_delete=django.db.models.deletion.PROTECT, to='Sagenkarta-Admin.Socken'),
        ),
        migrations.AlterField(
            model_name='transcribedrecordsplaces',
            name='record',
            field=models.ForeignKey(db_column='record', on_delete=django.db.models.deletion.PROTECT, to='Sagenkarta-Admin.TranscribedRecords'),
        ),
    ]
