# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-10-30 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sagenkarta-Admin', '0004_auto_20191030_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='changedate',
            field=models.DateTimeField(auto_now=True, verbose_name='Ändrad datum'),
        ),
        migrations.AddField(
            model_name='categories',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default='1900-01-01', verbose_name='Skapad datum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Excerperad av'),
        ),
        migrations.AddField(
            model_name='categories',
            name='editedby',
            field=models.ForeignKey(blank=True, db_column='editedby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uppdaterad av+', to=settings.AUTH_USER_MODEL, verbose_name='Uppdaterad av'),
        ),
    ]
