# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-04 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sagenkarta-Admin', '0008_auto_20191104_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsplaces',
            name='changedate',
            field=models.DateTimeField(auto_now=True, verbose_name='Ändrad datum'),
        ),
        migrations.AddField(
            model_name='personsplaces',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default='1900-01-01', verbose_name='Skapad datum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personsplaces',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Excerperad av'),
        ),
        migrations.AddField(
            model_name='personsplaces',
            name='editedby',
            field=models.ForeignKey(blank=True, db_column='editedby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uppdaterad av+', to=settings.AUTH_USER_MODEL, verbose_name='Uppdaterad av'),
        ),
        migrations.AddField(
            model_name='recordscategory',
            name='changedate',
            field=models.DateTimeField(auto_now=True, verbose_name='Ändrad datum'),
        ),
        migrations.AddField(
            model_name='recordscategory',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default='1900-01-01', verbose_name='Skapad datum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordscategory',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Excerperad av'),
        ),
        migrations.AddField(
            model_name='recordscategory',
            name='editedby',
            field=models.ForeignKey(blank=True, db_column='editedby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uppdaterad av+', to=settings.AUTH_USER_MODEL, verbose_name='Uppdaterad av'),
        ),
        migrations.AddField(
            model_name='recordsmedia',
            name='changedate',
            field=models.DateTimeField(auto_now=True, verbose_name='Ändrad datum'),
        ),
        migrations.AddField(
            model_name='recordsmedia',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default='1900-01-01', verbose_name='Skapad datum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordsmedia',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Excerperad av'),
        ),
        migrations.AddField(
            model_name='recordsmedia',
            name='editedby',
            field=models.ForeignKey(blank=True, db_column='editedby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uppdaterad av+', to=settings.AUTH_USER_MODEL, verbose_name='Uppdaterad av'),
        ),
        migrations.AddField(
            model_name='recordsmetadata',
            name='changedate',
            field=models.DateTimeField(auto_now=True, verbose_name='Ändrad datum'),
        ),
        migrations.AddField(
            model_name='recordsmetadata',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default='1900-01-01', verbose_name='Skapad datum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordsmetadata',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Excerperad av'),
        ),
        migrations.AddField(
            model_name='recordsmetadata',
            name='editedby',
            field=models.ForeignKey(blank=True, db_column='editedby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uppdaterad av+', to=settings.AUTH_USER_MODEL, verbose_name='Uppdaterad av'),
        ),
        migrations.AddField(
            model_name='recordspersons',
            name='changedate',
            field=models.DateTimeField(auto_now=True, verbose_name='Ändrad datum'),
        ),
        migrations.AddField(
            model_name='recordspersons',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default='1900-01-01', verbose_name='Skapad datum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordspersons',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Excerperad av'),
        ),
        migrations.AddField(
            model_name='recordspersons',
            name='editedby',
            field=models.ForeignKey(blank=True, db_column='editedby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uppdaterad av+', to=settings.AUTH_USER_MODEL, verbose_name='Uppdaterad av'),
        ),
        migrations.AddField(
            model_name='recordsplaces',
            name='changedate',
            field=models.DateTimeField(auto_now=True, verbose_name='Ändrad datum'),
        ),
        migrations.AddField(
            model_name='recordsplaces',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default='1900-01-01', verbose_name='Skapad datum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordsplaces',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Excerperad av'),
        ),
        migrations.AddField(
            model_name='recordsplaces',
            name='editedby',
            field=models.ForeignKey(blank=True, db_column='editedby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uppdaterad av+', to=settings.AUTH_USER_MODEL, verbose_name='Uppdaterad av'),
        ),
        migrations.AddField(
            model_name='sockenv1',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default='1900-01-01', verbose_name='Skapad datum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sockenv1',
            name='createdby',
            field=models.ForeignKey(blank=True, db_column='createdby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Excerperad av'),
        ),
        migrations.AddField(
            model_name='sockenv1',
            name='editedby',
            field=models.ForeignKey(blank=True, db_column='editedby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uppdaterad av+', to=settings.AUTH_USER_MODEL, verbose_name='Uppdaterad av'),
        ),
        migrations.AlterField(
            model_name='sockenv1',
            name='changedate',
            field=models.DateTimeField(auto_now=True, verbose_name='Ändrad datum'),
        ),
    ]
