# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sagenkarta-Admin', '0014_auto_20191112_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='approvedate',
            field=models.DateTimeField(blank=True, default='1900-01-01', verbose_name='Godkänd datum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='records',
            name='approvedby',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
