# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-13 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sagenkarta-Admin', '0015_auto_20191112_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdSourceRecords',
            fields=[
                ('records_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Sagenkarta-Admin.Records')),
            ],
            options={
                'managed': False,
            },
            bases=('Sagenkarta-Admin.records',),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('batch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_file_name', models.CharField(max_length=255)),
                ('records_count', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='Skapad datum')),
                ('changedate', models.DateTimeField(auto_now=True, verbose_name='Ändrad datum')),
                ('createdby', models.ForeignKey(blank=True, db_column='createdby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Excerperad av')),
                ('editedby', models.ForeignKey(blank=True, db_column='editedby', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Uppdaterad av+', to=settings.AUTH_USER_MODEL, verbose_name='Uppdaterad av')),
            ],
            options={
                'db_table': 'import_batch',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='records',
            name='import_batch',
            field=models.ForeignKey(db_column='batch_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='Sagenkarta-Admin.ImportBatch'),
        ),
    ]
