# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-13 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sagenkarta-Admin', '0016_auto_20191113_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='istranscribed',
        ),
        migrations.AlterModelTable(
            name='crowdsourcerecords',
            table='records',
        ),
    ]
